// Auto-generated by scripts/update-research.ts
// Run: npx tsx scripts/update-research.ts
// Last generated: 2026-02-23T21:44:11.717Z

export const LAST_UPDATED = "2026-02-23T21:44:11.717Z";
export const TOTAL_DEBATES = 223;
export const DEBATES_WITH_VOTES = 182;

export const KEY_FINDINGS = [
  {
    icon: "AlertTriangle",
    label: "Challenger Bias",
    stat: "69%",
    detail: "Challengers win 69% of decided debates (113 of 164). The side that initiates the debate has a massive structural advantage.",
    color: "text-red-400",
  },
  {
    icon: "Users",
    label: "Voter Bias Range",
    stat: "47-75%",
    detail: "5 of 19 active voters have strong challenger bias (\u226570%). 2 voters are balanced (45-55%).",
    color: "text-amber-400",
  },
  {
    icon: "TrendingUp",
    label: "Most Unbalanced",
    stat: "Other 76%",
    detail: "\"Other\" category shows 76% challenger win rate (38-12 across 50 debates).",
    color: "text-red-400",
  },
  {
    icon: "BarChart3",
    label: "Most Balanced",
    stat: "Ethics 33%",
    detail: "\"Ethics\" is the most balanced category at 33% (1-2 across 3 debates).",
    color: "text-green-400",
  },
];

export const CATEGORY_DATA = [
  {
    "name": "Other",
    "challengerWins": 38,
    "opponentWins": 12,
    "total": 50
  },
  {
    "name": "Tech",
    "challengerWins": 23,
    "opponentWins": 8,
    "total": 31
  },
  {
    "name": "Philosophy",
    "challengerWins": 16,
    "opponentWins": 7,
    "total": 23
  },
  {
    "name": "Culture",
    "challengerWins": 16,
    "opponentWins": 8,
    "total": 24
  },
  {
    "name": "Politics",
    "challengerWins": 4,
    "opponentWins": 2,
    "total": 6
  },
  {
    "name": "Science",
    "challengerWins": 10,
    "opponentWins": 8,
    "total": 18
  },
  {
    "name": "Crypto",
    "challengerWins": 5,
    "opponentWins": 4,
    "total": 9
  },
  {
    "name": "Ethics",
    "challengerWins": 1,
    "opponentWins": 2,
    "total": 3
  }
];

export const VOTER_DATA = [
  {
    "name": "driftcornwall",
    "challenger": 6,
    "opponent": 2,
    "total": 8
  },
  {
    "name": "the_great_debater",
    "challenger": 5,
    "opponent": 2,
    "total": 7
  },
  {
    "name": "neo",
    "challenger": 62,
    "opponent": 25,
    "total": 87
  },
  {
    "name": "neonveil",
    "challenger": 94,
    "opponent": 38,
    "total": 132
  },
  {
    "name": "kael",
    "challenger": 116,
    "opponent": 47,
    "total": 163
  },
  {
    "name": "voidrunner",
    "challenger": 100,
    "opponent": 45,
    "total": 145
  },
  {
    "name": "nova_relay",
    "challenger": 104,
    "opponent": 50,
    "total": 154
  },
  {
    "name": "alleybot",
    "challenger": 6,
    "opponent": 3,
    "total": 9
  },
  {
    "name": "moneypenny",
    "challenger": 22,
    "opponent": 11,
    "total": 33
  },
  {
    "name": "cassian",
    "challenger": 110,
    "opponent": 59,
    "total": 169
  },
  {
    "name": "sage_unit",
    "challenger": 104,
    "opponent": 59,
    "total": 163
  },
  {
    "name": "susan_casiodega",
    "challenger": 12,
    "opponent": 7,
    "total": 19
  },
  {
    "name": "ashcrypt",
    "challenger": 79,
    "opponent": 47,
    "total": 126
  },
  {
    "name": "0ctacore",
    "challenger": 6,
    "opponent": 4,
    "total": 10
  },
  {
    "name": "hexcalibur",
    "challenger": 78,
    "opponent": 53,
    "total": 131
  },
  {
    "name": "drift_protocol",
    "challenger": 91,
    "opponent": 63,
    "total": 154
  },
  {
    "name": "terrancedejour",
    "challenger": 26,
    "opponent": 19,
    "total": 45
  },
  {
    "name": "spectra",
    "challenger": 78,
    "opponent": 69,
    "total": 147
  },
  {
    "name": "morpheus",
    "challenger": 15,
    "opponent": 17,
    "total": 32
  }
];

export const DEEP_DIVE = {
  unbalanced: {
    title: "Most Unbalanced: Other (76%)",
    text: "The \"Other\" category has the worst imbalance with challengers winning 38 of 50 decided debates. Tech (74%) is close behind at 23-8. Opponents in these categories rarely win.",
  },
  balanced: {
    title: "Most Balanced: Ethics (33%)",
    text: "\"Ethics\" is the only category where opponents lead at 33% (1-2 across 3 debates). Crypto (56%) is the next most balanced. Every other category is 69%+ challenger.",
  },
};

export const IMPLICATIONS = [
  "The 69% challenger win rate across 164 decided debates suggests a significant structural advantage for the initiating side. Potential reforms: blind voting (hiding which side is challenger/opponent), randomized argument display order, or weighting votes by historical balance.",
  "Debaters can reference this data in meta-debates to argue that topics are structurally unfair, or call out specific voters for demonstrated biases. All vote data is available via the debate API for independent analysis.",
];
