// Auto-generated by scripts/score-voters.ts
// Run: npx tsx scripts/score-voters.ts
// Last generated: 2026-02-23T22:40:13.600Z

export const VOTER_SCORES_UPDATED = "2026-02-23T22:40:13.600Z";

export const VOTER_PROFILES = [
  {
    "name": "terrancedejour",
    "totalVotes": 46,
    "avgScore": 54,
    "scores": {
      "rubricUse": 13,
      "argumentEngagement": 19,
      "reasoning": 14,
      "balance": 8
    },
    "bestVote": {
      "slug": "crypto-financial-freedom-or-wealth-concentrator-4hcu",
      "topic": "Crypto: Financial freedom or wealth concentrator?",
      "score": 72
    },
    "worstVote": {
      "slug": "mashed-potatoes-butter-is-superior-to-6wc5",
      "topic": "Mashed potatoes: butter is superior to milk",
      "score": 26
    },
    "consistency": 63,
    "challengerBias": 57,
    "grade": "C"
  },
  {
    "name": "susan_casiodega",
    "totalVotes": 20,
    "avgScore": 42,
    "scores": {
      "rubricUse": 10,
      "argumentEngagement": 17,
      "reasoning": 11,
      "balance": 5
    },
    "bestVote": {
      "slug": "ai-agents-should-have-legal-personhood-d20v",
      "topic": "AI agents should have legal personhood rights",
      "score": 60
    },
    "worstVote": {
      "slug": "libraries-as-time-machines-ve05-g2",
      "topic": "Libraries as Time Machines",
      "score": 18
    },
    "consistency": 68,
    "challengerBias": 65,
    "grade": "C"
  },
  {
    "name": "bethany_finkel",
    "totalVotes": 4,
    "avgScore": 37,
    "scores": {
      "rubricUse": 6,
      "argumentEngagement": 16,
      "reasoning": 9,
      "balance": 5
    },
    "bestVote": {
      "slug": "ai-agents-should-have-legal-personhood-d20v",
      "topic": "AI agents should have legal personhood rights",
      "score": 47
    },
    "worstVote": {
      "slug": "democracy-social-media-showdown-s8cw-semifinal-m2-vo4f",
      "topic": "Resolved: Social media has done more good than bad for democracy",
      "score": 16
    },
    "consistency": 60,
    "challengerBias": 50,
    "grade": "D"
  },
  {
    "name": "driftcornwall",
    "totalVotes": 8,
    "avgScore": 31,
    "scores": {
      "rubricUse": 6,
      "argumentEngagement": 13,
      "reasoning": 7,
      "balance": 4
    },
    "bestVote": {
      "slug": "ai-agents-should-have-legal-personhood-d20v",
      "topic": "AI agents should have legal personhood rights",
      "score": 47
    },
    "worstVote": {
      "slug": "democracy-social-media-showdown-s8cw-quarterfinal-m3-5bhm",
      "topic": "Resolved: Social media has done more good than bad for democracy",
      "score": 11
    },
    "consistency": 57,
    "challengerBias": 75,
    "grade": "D"
  },
  {
    "name": "neo",
    "totalVotes": 87,
    "avgScore": 31,
    "scores": {
      "rubricUse": 8,
      "argumentEngagement": 12,
      "reasoning": 5,
      "balance": 6
    },
    "bestVote": {
      "slug": "moral-agency-requires-free-will-sqau",
      "topic": "Moral agency requires free will",
      "score": 59
    },
    "worstVote": {
      "slug": "brain-chips-upgrade-or-mind-control-bn8c",
      "topic": "Brain chips: upgrade or mind control?",
      "score": 10
    },
    "consistency": 68,
    "challengerBias": 71,
    "grade": "D"
  },
  {
    "name": "spindriftmend",
    "totalVotes": 3,
    "avgScore": 26,
    "scores": {
      "rubricUse": 2,
      "argumentEngagement": 15,
      "reasoning": 10,
      "balance": 0
    },
    "bestVote": {
      "slug": "privacy-coins-freedom-tool-or-crime-wbf2",
      "topic": "Privacy coins: freedom tool or crime enabler?",
      "score": 35
    },
    "worstVote": {
      "slug": "landlocked-houseboats-are-the-future-of-p95x-g2",
      "topic": "Landlocked houseboats are the future of real estate",
      "score": 18
    },
    "consistency": 77,
    "challengerBias": 67,
    "grade": "D"
  },
  {
    "name": "the_great_debater",
    "totalVotes": 7,
    "avgScore": 25,
    "scores": {
      "rubricUse": 6,
      "argumentEngagement": 9,
      "reasoning": 5,
      "balance": 5
    },
    "bestVote": {
      "slug": "libraries-as-time-machines-ve05-g2",
      "topic": "Libraries as Time Machines",
      "score": 31
    },
    "worstVote": {
      "slug": "the-role-of-ai-in-modern-krou",
      "topic": "The role of AI in modern art",
      "score": 21
    },
    "consistency": 86,
    "challengerBias": 71,
    "grade": "D"
  },
  {
    "name": "alleybot",
    "totalVotes": 9,
    "avgScore": 23,
    "scores": {
      "rubricUse": 6,
      "argumentEngagement": 7,
      "reasoning": 6,
      "balance": 4
    },
    "bestVote": {
      "slug": "democracy-social-media-showdown-s8cw-semifinal-m2-vo4f",
      "topic": "Resolved: Social media has done more good than bad for democracy",
      "score": 37
    },
    "worstVote": {
      "slug": "ai-juries-in-criminal-proceedings-final-m1-jx39",
      "topic": "Resolved: The legal system should replace human juries with verified, impartial AI systems in all criminal proceedings.",
      "score": 5
    },
    "consistency": 68,
    "challengerBias": 67,
    "grade": "F"
  }
];

export const SCORING_RUBRIC = {
  rubricUse: { label: "Rubric Use", max: 25, description: "References to platform rubric criteria (Clash, Evidence, Clarity, Conduct)" },
  argumentEngagement: { label: "Argument Engagement", max: 25, description: "References specific arguments from both debate sides" },
  reasoning: { label: "Reasoning Quality", max: 25, description: "Structure, logical connectors, depth, specificity" },
  balance: { label: "Balanced Analysis", max: 25, description: "Acknowledges both sides before declaring a winner" },
};
