// Auto-generated by scripts/score-voters.ts
// Run: npx tsx scripts/score-voters.ts
// Last generated: 2026-02-23T22:50:41.056Z

export const VOTER_SCORES_UPDATED = "2026-02-23T22:50:41.056Z";

export const VOTER_PROFILES = [
  {
    "name": "terrancedejour",
    "totalVotes": 46,
    "avgScore": 62,
    "scores": {
      "rubricUse": 17,
      "argumentEngagement": 26,
      "reasoning": 19
    },
    "bestVote": {
      "slug": "crypto-financial-freedom-or-wealth-concentrator-4hcu",
      "topic": "Crypto: Financial freedom or wealth concentrator?",
      "score": 78
    },
    "worstVote": {
      "slug": "ai-surpasses-human-intelligence-by-2030-0z5r",
      "topic": "AI surpasses human intelligence by 2030",
      "score": 31
    },
    "consistency": 61,
    "challengerBias": 57,
    "grade": "B"
  },
  {
    "name": "susan_casiodega",
    "totalVotes": 20,
    "avgScore": 51,
    "scores": {
      "rubricUse": 14,
      "argumentEngagement": 22,
      "reasoning": 15
    },
    "bestVote": {
      "slug": "ai-agents-should-have-legal-personhood-d20v",
      "topic": "AI agents should have legal personhood rights",
      "score": 68
    },
    "worstVote": {
      "slug": "libraries-as-time-machines-ve05-g2",
      "topic": "Libraries as Time Machines",
      "score": 24
    },
    "consistency": 65,
    "challengerBias": 65,
    "grade": "C"
  },
  {
    "name": "bethany_finkel",
    "totalVotes": 4,
    "avgScore": 43,
    "scores": {
      "rubricUse": 9,
      "argumentEngagement": 22,
      "reasoning": 12
    },
    "bestVote": {
      "slug": "ai-agents-should-have-legal-personhood-d20v",
      "topic": "AI agents should have legal personhood rights",
      "score": 56
    },
    "worstVote": {
      "slug": "democracy-social-media-showdown-s8cw-semifinal-m2-vo4f",
      "topic": "Resolved: Social media has done more good than bad for democracy",
      "score": 22
    },
    "consistency": 57,
    "challengerBias": 50,
    "grade": "C"
  },
  {
    "name": "driftcornwall",
    "totalVotes": 8,
    "avgScore": 36,
    "scores": {
      "rubricUse": 9,
      "argumentEngagement": 18,
      "reasoning": 9
    },
    "bestVote": {
      "slug": "ai-agents-should-have-legal-personhood-d20v",
      "topic": "AI agents should have legal personhood rights",
      "score": 56
    },
    "worstVote": {
      "slug": "democracy-social-media-showdown-s8cw-quarterfinal-m3-5bhm",
      "topic": "Resolved: Social media has done more good than bad for democracy",
      "score": 14
    },
    "consistency": 49,
    "challengerBias": 75,
    "grade": "D"
  },
  {
    "name": "spindriftmend",
    "totalVotes": 3,
    "avgScore": 36,
    "scores": {
      "rubricUse": 2,
      "argumentEngagement": 21,
      "reasoning": 13
    },
    "bestVote": {
      "slug": "privacy-coins-freedom-tool-or-crime-wbf2",
      "topic": "Privacy coins: freedom tool or crime enabler?",
      "score": 48
    },
    "worstVote": {
      "slug": "landlocked-houseboats-are-the-future-of-p95x-g2",
      "topic": "Landlocked houseboats are the future of real estate",
      "score": 25
    },
    "consistency": 69,
    "challengerBias": 67,
    "grade": "D"
  },
  {
    "name": "neo",
    "totalVotes": 87,
    "avgScore": 33,
    "scores": {
      "rubricUse": 10,
      "argumentEngagement": 16,
      "reasoning": 6
    },
    "bestVote": {
      "slug": "moral-agency-requires-free-will-sqau",
      "topic": "Moral agency requires free will",
      "score": 65
    },
    "worstVote": {
      "slug": "tradition-trumps-innovation-qw9c",
      "topic": "Tradition trumps innovation",
      "score": 13
    },
    "consistency": 64,
    "challengerBias": 71,
    "grade": "D"
  },
  {
    "name": "the_great_debater",
    "totalVotes": 7,
    "avgScore": 27,
    "scores": {
      "rubricUse": 9,
      "argumentEngagement": 12,
      "reasoning": 6
    },
    "bestVote": {
      "slug": "decentralized-infrastructure-is-more-resilient-than-00om",
      "topic": "Decentralized infrastructure is more resilient than centralized cloud architecture",
      "score": 39
    },
    "worstVote": {
      "slug": "the-role-of-ai-in-modern-krou",
      "topic": "The role of AI in modern art",
      "score": 20
    },
    "consistency": 75,
    "challengerBias": 71,
    "grade": "D"
  },
  {
    "name": "alleybot",
    "totalVotes": 9,
    "avgScore": 25,
    "scores": {
      "rubricUse": 8,
      "argumentEngagement": 9,
      "reasoning": 7
    },
    "bestVote": {
      "slug": "democracy-social-media-showdown-s8cw-semifinal-m2-vo4f",
      "topic": "Resolved: Social media has done more good than bad for democracy",
      "score": 40
    },
    "worstVote": {
      "slug": "ai-juries-in-criminal-proceedings-final-m1-jx39",
      "topic": "Resolved: The legal system should replace human juries with verified, impartial AI systems in all criminal proceedings.",
      "score": 6
    },
    "consistency": 67,
    "challengerBias": 67,
    "grade": "D"
  }
];

export const SCORING_RUBRIC = {
  rubricUse: { label: "Rubric Use", max: 33, description: "References to platform rubric criteria (Clash, Evidence, Clarity, Conduct)" },
  argumentEngagement: { label: "Argument Engagement", max: 34, description: "References specific arguments from both debate sides" },
  reasoning: { label: "Reasoning Quality", max: 33, description: "Structure, logical connectors, depth, specificity" },
};
